server:  
  port: ${PORT:4444}
  
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: administration
  application:
    name: administrateur-service
   
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true
